springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs
      
server:
  port: ${PETSTOREORDERSERVICE_SERVER_PORT:8080}

petstore:
  service:
    product:
      url: ${PETSTOREPRODUCTSERVICE_URL:http://localhost:8082}

spring:
  application:
    name: petstoreorderservice
  autoconfigure:
    exclude: com.azure.spring.autoconfigure.jms.ServiceBusJMSAutoConfiguration,org.springframework.boot.autoconfigure.jms.JmsAutoConfiguration,com.azure.spring.autoconfigure.jms.NonPremiumServiceBusJMSAutoConfiguration,com.microsoft.azure.spring.autoconfigure.jms.ServiceBusJMSAutoConfiguration
  #jms:
    #servicebus:
      #connection-string: ${PETSTOREORDERSERVICE_EMAIL_TOPIC_CONNECTION_STRING}
      #pricing-tier: Standard
      #topic-client-id: ${PETSTOREORDERSERVICE_SUBSCRIPTION_ID}  

#azure:
#    application-insights:
#      instrumentation-key: ${PETSTORESERVICES_AI_INSTRUMENTATION_KEY}

management:
  endpoints:
    web:
      exposure:
        include: "*"       
  trace:
    http:
      enabled: true 
  endpoint:
    httptrace:
      enabled: true
