import os
from dotenv import load_dotenv

load_dotenv()

AZURE_OPENAI_ENDPOINT = os.getenv("AZURE_OPENAI_ENDPOINT")
AZURE_OPENAI_API_KEY = os.getenv("AZURE_OPENAI_API_KEY")
AZURE_OPENAI_DEPLOYMENT_NAME = os.getenv("AZURE_OPENAI_DEPLOYMENT_NAME")
AZURE_OPENAI_SERVICE_VERSION = os.getenv("AZURE_OPENAI_SERVICE_VERSION")
AZURE_PETSTORE_SESSIONID=os.getenv("AZURE_PETSTORE_SESSIONID")
AZURE_PETSTORE_CSRF=os.getenv("AZURE_PETSTORE_CSRF")